name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  call-shared-workflow:
    uses: JuozasVainauskas/gh-shared-workflows-test/.github/workflows/test-workflow.yaml@main
